accounts/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('register',views.register,name="register"),
    path('login',views.login,name="login"),
    path('logout',views.logout,name="logout"),

] 

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('part1.urls')),
     path('accounts/',include('accounts.urls')),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

part1/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path('',views.index,name="Homepage"),
    path('postdetail',views.postdetail,name="postdetail"),
    path('createpost',views.createpost,name="createpost"),
    path('profile',views.profile,name="profile"),
    path('editpost',views.editpost,name="editpost"),
    path('puborsaveeditpost',views.puborsaveeditpost,name="publisheditedpost"),

] 

accounts/models.py
from django.db import models

# Create your models here.

part1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Userinfo(models.Model):
    username= models.CharField(max_length=100,unique=True)
    fname= models.CharField(max_length=100)
    lname= models.CharField(max_length=100)
    email= models.CharField(max_length=100)

class Posts(models.Model):
    username= models.ForeignKey(Userinfo, to_field='username', db_column='username',on_delete=models.CASCADE)
    title =models.CharField(max_length=100)
    content= models.TextField()
    createdon = models.DateTimeField(auto_now_add=True)
    updatedon=models.DateTimeField(auto_now= True)
    status = models.IntegerField( default=0)
    img = models.ImageField(upload_to='pics')
    seen_no = models.IntegerField()

class Postsdata(models.Model):
    uname= models.ForeignKey(User,on_delete=models.CASCADE)
    title =models.CharField(max_length=100)
    content= models.TextField()
    createdon = models.DateTimeField(auto_now_add=True)
    updatedon=models.DateTimeField(auto_now= True)
    status = models.IntegerField( default=0)
    img = models.ImageField(upload_to='pics')
    seen_no = models.IntegerField( default=0)

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
from django.contrib import messages

# Create your views here.

def register(request):
    flag = 0
    if request.method=='POST':
        uname=request.POST['username']
        fname=request.POST['fname']
        lname=request.POST['lname']
        emaill=request.POST['emaill']
        passwords=request.POST['passwords']
        cpasswords=request.POST['confirmpassword']

        if passwords==cpasswords :
            if User.objects.filter(username=uname).exists() or User.objects.filter(email=emaill).exists() :
                messages.info(request,'Username or Email already taken :(')
                return redirect('register')
            else:
                user = User.objects.create_user(username=uname,password=passwords,email=emaill,first_name=fname,last_name=lname)
                user.save()
                user = auth.authenticate(username=uname ,password=passwords)
                if user is not None:
                    auth.login(request,user)
                    return redirect('/')
        else :
            messages.info(request,'Please enter the same passwords!!')
            return redirect('register')
            
    else:
        return render(request,'temp3.html')


def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user = auth.authenticate(username=username ,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,'Incorrect Credentials')
            return redirect('login')

    else:
        return render(request,'temp4.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

part1/views.py
from django.shortcuts import render,redirect
from part1.models import Posts,Postsdata
from django.contrib import messages


# Create your views here.

def index(request):
    posts = Postsdata.objects.filter(status=1).order_by('-createdon')
    
    return render(request,'temp1.html',{'post': posts})

def postdetail(request):
    if request.method=='POST':
        pid=request.POST['pid']
        post = Postsdata.objects.filter(id=pid)
        for p in post:
            p.seen_no +=1
            p.save()
        return render(request,'temp2.html',{'post':post})

def createpost(request):
    if request.user.is_authenticated:
        if request.method=='POST':
            title=request.POST['title']
            content=request.POST['content']
            if request.POST.get('publish'):
                status=1
            elif request.POST.get('save'):
                status=0
            pd =Postsdata(uname=request.user,title=title,content=content,status=status)
            pd.save()
            messages.info(request,'Changes Done')
            return redirect('/')
        else:
            return render(request,'temp5.html')
    else:
        return redirect('login')

def profile(request):
    posts = Postsdata.objects.filter(uname=request.user,status=0).order_by('-createdon') 
    return render(request,'temp6.html',{'post': posts})

def editpost(request):
    if request.method=='POST':
        pid=request.POST['pid']
        post = Postsdata.objects.filter(id=pid)
        return render(request,'temp7.html',{'post':post})

def puborsaveeditpost(request):
    if request.method=='POST':
            title=request.POST['title']
            content=request.POST['content']
            pid=request.POST['pid']
            if request.POST.get('publish'):
                status=1
            elif request.POST.get('save'):
                status=0
            pd = Postsdata.objects.get(id = pid)
            pd.title = title
            pd.content = content
            pd.status=status
            pd.save()
            messages.info(request,'Changes Done')
            return redirect('profile')

        

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Website</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    
  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
      }

    .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }
     
     .masthead {
              background:#3398E1;
              height: auto;
              padding-bottom: 15px;
              box-shadow: 0 16px 48px #E3E7EB;
              padding-top: 10px;
    }
    </style>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="" >Blog Website</a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
       
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
		  <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="/">Read</a>
              </li>
            <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="createpost">Write</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="profile">Profile</a>
              </li>
              <li class="nav-item text-black">
                <a class="nav-link text-black font-weight-bold" href="accounts/logout">Logout</a>
              </li>
              {%else%}
			  <li class="nav-item text-black">
              <a class="nav-link text-black font-weight-bold" href="accounts/register">Register</a>
            </li>
            <li class="nav-item text-black">
              <a class="nav-link text-black font-weight-bold" href="accounts/login">Log in</a>
            </li>
            {%endif%}
            <li class="nav-item text-black">
              <a class="nav-link text-black font-weight-bold" href="#" >Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    </nav>
    

            {% block content %} 
          <!-- Content Goes here -->
            {% endblock content %}
    
    <!-- Footer -->
    <footer class="py-3 bg-grey">
              <p class="m-0 text-dark text-center ">Copyright &copy; xyz</p>
    </footer>
    
  </body>
</html>

templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
        <a href="#"
           class="btn btn-danger">Know more!</a>
    </div>
</div>
</div>

{% endblock sidebar %}

templates/temp1.html
{% extends 'base.html' %} 
{% block content %}

{% for p in post %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ p.title }} {% endblock title %}</h1>
        <p class=" text-muted">Author : {{ p.uname }} | Published on : {{ p.createdon }} | Views : {{ p.seen_no }}</p>
        <p class="card-text">{{p.content|slice:":200" }}</p>
        <form action="postdetail" method="post">
          {% csrf_token %}
          {{ form }}
          <input type="hidden" name="pid" value="{{p.id}}">
          <input type="submit" class="btn btn-primary" value="Read More" />
          </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock content %}

templates/temp2.html
{% extends 'base.html' %} {% block content %}
{% for p in post %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ p.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ p.uname }} | {{ p.createdon }}</p>
        <p class="card-text ">{{ p.content | safe }}</p>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/temp3.html
<html lang="en-us"><head>
    <title>User Registration</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
      <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
      <script src="/static/admin/js/nav_sidebar.js" defer=""></script>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    </head>
    <body class=" login" data-admin-utc-offset="0">
    <!-- Container -->
    <div id="container">
        <!-- Header -->
        <div id="header">
            <div id="branding">    
    <h1 id="site-name"><a href=""></a>User Registration</h1>
            </div>  
        </div>
        <!-- END Header -->
        <div class="main shifted" id="main"> 
          <div class="content">
            <!-- Content -->
            <div id="content" class="colM">
    <div id="content-main">
    <form action="register" method="post" >
      {% csrf_token %}
      <div class="form-row">  
        <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="100" required="" id="id_username">
        <input type="hidden" name="next" value="/admin/">
      </div>
      <div class="form-row">  
        <label class="required" for="id_fname">First Name:</label> <input type="text" name="fname" autofocus="" autocapitalize="none" autocomplete="fname" maxlength="100" required="" id="id_fname">
        <input type="hidden" name="next" value="/admin/">
      </div>
      <div class="form-row">  
        <label class="required" for="id_lname">Last Name:</label> <input type="text" name="lname" autofocus="" autocapitalize="none" autocomplete="lname" maxlength="100" required="" id="id_lname">
        <input type="hidden" name="next" value="/admin/">
      </div>
      <div class="form-row">  
        <label class="required" for="id_email">Email:</label> <input type="email" name="emaill" autofocus="" autocapitalize="none" autocomplete="email" maxlength="100" required="" id="id_email">
        <input type="hidden" name="next" value="/admin/">
      </div>
      <div class="form-row"> 
        <label class="required" for="id_password">Password:</label> <input type="password" name="passwords" autocomplete="current-password" required="" id="id_password">
        <input type="hidden" name="next" value="/admin/">
      </div>
      <div class="form-row"> 
        <label class="required" for="id_confirmpassword">Confirm Password:</label> <input type="password" name="confirmpassword" autocomplete="confirm-password" required="" id="id_confirmpassword">
        <input type="hidden" name="next" value="/admin/">
      </div>
      
      
      <div class="submit-row">
        <input type="submit" value="Register">
      </div>
    </form>
    
    </div>
    
              
              <br class="clear">
            </div>
            <!-- END Content -->
            <div id="footer"></div>
          </div>
        </div>
    </div>
    <!-- END Container -->
  <div>
    {%for message in messages%}
    <h4>{{message}}</h4>
    {%endfor%}
  </div>
    
    
    
    </body></html>

templates/temp4.html
<html lang="en-us"><head>
    <title>Log in</title>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    
      <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
      <script src="/static/admin/js/nav_sidebar.js" defer=""></script>
    
    <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
        <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <meta name="robots" content="NONE,NOARCHIVE">
    </head>
    <body class=" login" data-admin-utc-offset="0">
    <!-- Container -->
    <div id="container">
        <!-- Header -->
        <div id="header">
            <div id="branding">    
    <h1 id="site-name"><a href="">User Log in</a></h1>
            </div>  
        </div>
        <!-- END Header -->
        <div class="main shifted" id="main"> 
          <div class="content">
            <!-- Content -->
            <div id="content" class="colM">
    <div id="content-main">
    <form action="login" method="post" id="login-form">
      {% csrf_token %}
      <div class="form-row">
        
        <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
      </div>
      <div class="form-row">
        
        <label class="required" for="id_password">Password:</label> <input type="password" name="password" autocomplete="current-password" required="" id="id_password">
        <input type="hidden" name="next" value="/admin/">
      </div>
      
      
      <div class="submit-row">
        <input type="submit" value="Log in">
      </div>
    </form>
    
    </div>
    
              
              <br class="clear">
            </div>
            <!-- END Content -->
            <div id="footer"></div>
          </div>
        </div>
    </div>
    <!-- END Container -->

    <div>
      {%for message in messages%}
      <h4>{{message}}</h4>
      {%endfor%}
    </div>
      
    
    
    </body></html>

templates/temp5.html
{% extends 'base.html' %} 
{% block content %}
<span class="border border-dark">
<div class="container">
    <div class="row">
        <div class="col-md-12 card mb-8">
<form action="createpost" method="post">
    {% csrf_token %}
    <div></div>
    <div class="form-group">
      <label for="exampleFormControlInput1">Title</label>
      <input type="text" class="form-control" name="title" id="exampleFormControlInput1" placeholder="Blog Title">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Blog Content</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" name="content" rows="14"></textarea>
    </div>
    <input type="submit"  class="btn btn-secondary" value="Save" name="save" />
    <input type="submit" class="btn btn-primary" value="Publish" name="publish" />
  </form>

</div>
</div>
</div>

<div>
    {%for message in messages%}
    <h4>{{message}}</h4>
    {%endfor%}
  </div>
</span>
{% endblock content %}

templates/temp6.html
{% extends 'base.html' %} 
{% block content %}

{% for p in post %}
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ p.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ p.uname }} | {{ p.createdon }}</p>
        <p class="card-text">{{p.content|slice:":200" }}</p>
        <form action="editpost" method="post">
          {% csrf_token %}
          {{ form }}
          <input type="hidden" name="pid" value="{{p.id}}">
          <input type="submit" class="btn btn-primary" value="Edit -->" />
          </form>
      </div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock content %}

templates/temp7.html
{% extends 'base.html' %} {% block content %}
{% for p in post %}
    <span class="border border-dark">
        <div class="container">
            <div class="row">
                <div class="col-md-12 card mb-8">
        <form action="puborsaveeditpost" method="post">
            {% csrf_token %}
            <div></div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Title</label>
              <input type="text" class="form-control" name="title" id="exampleFormControlInput1" value="{{p.title}}">
            </div>
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Blog Content</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" name="content" rows="14">{{p.content}}</textarea>
            </div>
            <input type="hidden" name="pid" value="{{p.id}}">
            <input type="submit"  class="btn btn-secondary" value="Save" name="save" />
            <input type="submit" class="btn btn-primary" value="Publish" name="publish" />
          </form>
        
        </div>
        </div>
        </div>
        
        <div>
            {%for message in messages%}
            <h4>{{message}}</h4>
            {%endfor%}
          </div>
        </span>
{% endfor %}
{% endblock content %}